set -g fish_color_normal %%color12%%
set -g fish_color_param %%color15%%
set -g fish_color_option %%color7%%
set -g fish_color_quote %%color7%%
set -g fish_color_comment %%color14%%
set -g fish_color_autosuggestion %%color14%%
set -g fish_color_operator %%color7%%
set -g fish_color_redirection %%color7%%
set -g fish_color_escape %%color15%%
set -g fish_color_end %%color7%%
set -g fish_color_cwd %%color15%%
set -g fish_color_user %%color15%%
set -g fish_color_host %%color7%%
set -g fish_pager_color_prefix %%color15%%
set -g fish_pager_color_description %%color14%%
