Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gdk/UnscaledDPI 132710
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout "icon:minimize,maximize,close"
Net/ThemeName "Breeze-Dark"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Gtk/CursorThemeSize 32
Gtk/CursorThemeName "breeze_cursors"
Net/SoundThemeName "ocean"
Net/IconThemeName "a-candy-beauty-icon-theme"
Gtk/FontName "FiraCode Nerd Font Mono,  10"

